metadata:
  name: ${project.artifactId}
  labels:
    app: ${project.artifactId}
    project: ${project.artifactId}
    hystrix.enabled: true
    hystrix.cluster: default
    version: ${project.version}
    group: ${project.groupId}
spec:
  replicas: ${k8s.deployment.replicas}
  selector:
    matchLabels:
      app: ${project.artifactId}
      group: ${project.groupId}
  template:
    metadata:
      name: ${project.artifactId}
      labels:
        app: ${project.artifactId}
        project: ${project.artifactId}
        hystrix.enabled: true
        hystrix.cluster: default
        version: ${project.version}
        group: ${project.groupId}
    spec:
      containers:
        - imagePullPolicy: Always
          name: ${project.artifactId}
          resources:
            requests:
              memory: ${k8s.deployment.mem.min}
            limits:
              memory: ${k8s.deployment.mem.max}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 3
      restartPolicy: Always
