metadata:
  labels:
    project: ${project.artifactId}
    hystrix.enabled: true
    hystrix.cluster: default
    version: ${project.version}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: ${project.artifactId}
        hystrix.enabled: true
        hystrix.cluster: default
        version: ${project.version}
    spec:
      containers:
        - resources:
            limits:
              memory: ${limits_memory}
            requests:
              memory: ${requests_memory}

