apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${project.artifactId}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: ${project.artifactId}
          servicePort: 8080
        path: /${project.artifactId}/(.*)
    host: ingress.dev.com
